### PR TITLE
Update docs and note new `ui.window(...)` more clearly

### PR DESCRIPTION
**Pull request by dbr**
Updates the README reflecting the changes to the gfx renderer, no more submodule. Also makes the glow examples easier to distinguish (since they all appear in `cargo run --example` if invoked at top-level of repo)

The CHANGELOG notes the major deprecation of `imgui::Window::new(...)` in favour of `ui.window(...)` and same for child_window. Also actually mark the function as deprecated

The latter part relates to #561 which rightly pointed out it wasn't clear why `Window::build` suddenly changed in a seemingly nonsensical weird way

### CODE REVIEW

**Comment by sanbox-irl** [comment]
pushed a rebase, but github says there are issues that weirdly my git isn't showing? On a flight and I suspect things are getting wonky! I'll merge this in this week, along with most issues in the project!

**Comment by dbr** [comment]
Strange, I think maybe the rebase went wrong somehow - based onto an older version of main branch perhaps, not sure

The pre-rebase commit eb072f2c5556a315c03b8c2a6aa9d33c65c549a0 only added about 4 commits, but the new PR is showing a bunch more including the submodule removal which are already merged :thinking:

**Comment by sanbox-irl** [comment]
HMM! Don't do rebases while flying lol. I suspect i rebased off my fork and not upstream. I'll fix but it's gonna be ugly. Probably will close this PR and remake cherry picked. Oops!

**Comment by sanbox-irl** [comment]
done in last commit bebd4168faed88e60850fd53415b182965ca79e0 because i'm an idiot (just cherry picked the changes)

**Pull request closed without merging**
