### PR TITLE
Remove ImStr and ImString

### PR DESCRIPTION
**Pull request by sanbox-irl**
This is still in progress but is quite close. Please let me know your thought. I am not done with the trait, but I do like the simplicity of this setup

### CODE REVIEW

**Comment by toyboot4e** [comment]
I'm liking th changes overall! Can't appliciate enough your effort :)

---

For now, `Ui::combo_simple_string` is taking a slice, but the doc says:

```
BREAKING: reworked `ComboBox` to be entirely on the `Ui` struct, and to make it much more flexible, taking iterators instead of slices.
```

Is it like WIP or changed?

**Comment by sanbox-irl** [comment]
@toyboot4e good catch! I changed it to use an iterator and then decided that shouldn't be in this PR (I was on an airplane and was truly going wild on the code base). I'll remove that comment, though I DID add the rest of the combo box functions

**Comment by sanbox-irl** [comment]
Okay! Please all, take a look and if you have opinions on these changes, let me know!

**Comment by imlazyeye** [comment]
yes, looks excellent, you have my blessing to merge this mr sanbox

**Comment by sanbox-irl** [comment]
me accepting my own pr:

**Pull request merged**
