### PR TITLE
allow creation of ui and context objects

### PR DESCRIPTION
**Pull request by greaka**
Hey there,
it is impossible to use imgui-rs in combination with a backend provided by an external c application.
This PR would allow creating the necessary instances of Context and Ui.

### CODE REVIEW

**Comment by sanbox-irl** [comment]
Hi! Thanks for the PR! 

On the surface, glancing over this, it seems to me like the worry would be that these operations aren't guarded, and competing calls could easily happen. A lot of the FFI safety in imgui-rs relies on it having unique access to the Context.

I'd be okay with a function like these at the minimum guarded around some unsafety, but I'd also probably be interested in some way that's more type aware as well to reduce unsafety. 

@thomcc you have a better handle on this area than I do

**Comment by greaka** [comment]
Thank you for the fast response!
I will happily adapt the PR as necessary.

Using it the way it is currently requires to never drop the created objects, or else bad things happen. So getting some guidance on how I can make it safe for other people to use is very much appreciated.

**Comment by thomcc** [comment]
It's probably fine if the API for this is unsafe (e.g. `unsafe fn`s). I'll think more though, busy this weekend (through to like Tuesday or so).

**Comment by greaka** [comment]
Hey there,
I just wanted to check in on this, any ideas? :slightly_smiling_face:

**Comment by greaka** [comment]
I completely forgot that I had this PR open, closing because it is dead anyway.

**Pull request closed without merging**
