### PR TITLE
Backport text-input bug fixes for 0.8.1

### PR DESCRIPTION
**Pull request by dbr**
I didn't quite realize there was over 100 commits since v0.8.0 (:partying_face:), so I might have missed something but I think this covers the bugfixes relating to the text input bugs

Backports the following changes:

- 5cf67c22d423559b6d0f0e67e92083db39c27ed4
- 6faa7f090a34ef16b5c3880d988caa95babb1aba
- daea06108f5d7c60742b8d71b4a0977585ce5a76

Relates to #564 #546 #553

Also there didn't seem to be any existing conventions for release-maintenance branch naming (I would normally use `maint-0.8` but interferes in minor way with tab-complete for `main`)

### CODE REVIEW

**Comment by cosmicchipsocket** [comment]
Wait, why is this going into main? Don't we want this in a new branch?

**Comment by dbr** [comment]
Oh yes good point, I wasn't clear! I don't intend this PR to be merged - these changes are already in the `release-0.8` branch where they should remain, this PR existing is just for review/visibility.

I've marked it as a draft to avoid the lure of clicking merge

**Comment by sanbox-irl** [comment]
okay @dbr @cosmicchipsocket let me know what you think? I think this is good to publish now

**Comment by dbr** [comment]
Looks good to me!

**Comment by cosmicchipsocket** [comment]
I haven't found any issues during my usage of the branch.

**Comment by sanbox-irl** [comment]
about to publish -- instead of a PR, did it as a seperate branch on the repo. i probably could have done that with this PR, but wasn't sure how!

**Comment by sanbox-irl** [comment]
aaah you had already done that. I am so sorry haha

**Pull request closed without merging**
