### PR TITLE
Update winit to 0.28

### LINKED ISSUE #713: Please Update winit 0.27.1 -> 0.28.1
**Is your feature request related to a problem? Please describe.**
Winit-Support uses Winit Old Version 0.27.1 lets switch to the newest one (0.28.1)

### PR DESCRIPTION
**Pull request by parasyte**
- Fixes #713

Alternative to #712

### CODE REVIEW

**Comment by parasyte** [comment]
This can't currently be done because `glium` is stuck on winit 0.27. And I don't don't think adding feature flags to `imgui-winit-support` to swap out winit versions is a good idea.

**Comment by junglie85** [comment]
Is there any update on when this change is expected to land?

**Comment by parasyte** [comment]
We are waiting for the upstream changes to glium. Can't realistically make progress without it.

**Comment by parasyte** [comment]
When it's released, all I have to do to move this forward is revert [b75d100](https://github.com/imgui-rs/imgui-rs/pull/716/commits/b75d100e3af750d645f2af69b4c1ff98a1bceaae) and update the dep. Along with any other changes required. (It looks like quite a list of breaking changes upstream from that PR. But that's just a guess.)

**Comment by dbr** [comment]
From https://github.com/glium/glium/pull/2074 it seems like the glium 0.33 release is very close

**Comment by barzamin** [comment]
fwiw, glium@0.33 just released! cc @parasyte

**Comment by parasyte** [comment]
Should be fixed by #754 and #765.

**Pull request closed without merging**
