### PR TITLE
Update to Dear ImGui 1.90.1

### PR DESCRIPTION
**Pull request by whitequark**
This is my first imgui-rs PR and my first time using Dear ImGui, so please forgive me if I've not quite followed the conventions of these bindings right. A few mechanisms were deprecated; none of them seem especially commonly used to me, so I haven't added any compatibility shims, and instead tried to stay as close to the upstream as possible.

I've done my best to keep the newly introduced entities (enums, mainly) complete but I haven't exposed all of them in the Rust API as this is a lot of work and the added APIs seem niche. I don't think I have the time to add them.

The motivation for this PR is [proper HiDPI support](https://github.com/ocornut/imgui/issues/1065#issuecomment-2212619726), which was merged in 1.90. It was harmless to upgrade to 1.90.1, so I've done that as well.

### CODE REVIEW

**Comment by salvatorebenedetto** [comment]
Hey @whitequark, thanks a lot for doing this. I also recently asked for it in #787 which has resizable window.

I'm not a maintainer but it would probably help maintainers if you can write what tests you executed to validate your upgrade. Thanks again for doing this. I hope it gets merged soon.

CC: @sanbox-irl who might be interested in this.

**Comment by whitequark** [comment]
> I'm not a maintainer but it would probably help maintainers if you can write what tests you executed to validate your upgrade.

I ran a few of the examples provided with all four of the possible Dear ImGui branches (all combinations of freetype and docking) and verified that they run reasonably well. I also checked that my own Dear ImGui based application works well.

**Comment by sanbox-irl** [comment]
Hi all! Sorry, the game I work on (fields of mistria) is nearing its release -- I'll try to take a look sooner (I'm keeping it high in my github notifications), but it's pinching my time pretty severely. I appreicate your work!

**Comment by whitequark** [comment]
No worries! That looks like a really cute game.

**Comment by salvatorebenedetto** [comment]
Any updates here @sanbox-irl ? Is there any other maintainer other than you who can take a look at this? Thanks.

**Comment by whitequark** [comment]
Note that I've decided to switch to egui since (the ergonomics of imgui-rs were too impairing for my project) so I'm not going to be updating this PR further.

**Comment by sanbox-irl** [comment]
Hi thanks for the effort! Yeah sorry, I was releasing the game I work on (called Fields of Mistria) and was just very busy. Going to try this weekend to make it through some imgui-rs work!

**Comment by sanbox-irl** [comment]
Closing this in favor of <https://github.com/imgui-rs/imgui-rs/pull/795>, which pulled in your changes. Thank you very much! As per your last message, I didn't think you'd want an extended back-and-forth, so I copied over much of your work and updated past to 1.91. You'll be thanked and credited in the Git comments and the release CI!

**Comment by whitequark** [comment]
Thanks, much appreciated!

**Pull request closed without merging**
