### PR TITLE
Add double input and allow setting display format

### LINKED ISSUE #489: Add InputDouble and display format settings for InputFloat and InputDouble
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the `InputFloat` fields only show three decimal places and there's no way to change it. Also I'd like to be able to use imgui's `InputDouble`.

**Describe the solution you'd like**
A `display_format` argument like it already exists for `Drag`, but for `InputFloat(N)` and `InputDouble`.

**Describe alternatives you've considered**
Multiplying the value by 10 or 100 to get more precision and being sad about it.

**Additional context**
I'll open a pull request for this.

### PR DESCRIPTION
**Pull request by EmbersArc**
Closes #489.

### CODE REVIEW

**Comment by thomcc** [comment]
This largely looks good, but I won't be able to actually review until next week (just got vaccinated and feel like crap at the moment).

Although, I'm not sure why CI didn't run after I clicked approve, hrm...

**Comment by EmbersArc** [comment]
No worries, get well soon!

**Comment by sanbox-irl** [comment]
Heya! Sorry this got lost in the shuffle.

We've since changed both how we handle number inputs and how we handle labels. Would you have time to rebase and tag me again when it can be merged with those changes?
If you don't have time, but still think this should merged, lmk and I'll handle the work for you too!

**Comment by EmbersArc** [comment]
Some strange git stuff happended. I'll open a new PR soon.

**Pull request closed without merging**
