### PR TITLE
remove VERSION file as it conflicts with c++ includes

### PR DESCRIPTION
**Pull request by benmkw**
closes https://github.com/imgui-rs/imgui-rs/issues/483

### CODE REVIEW

**Comment by thomcc** [comment]
Hm, sure. can you rename it to VERSION.txt instead though? I think some people may want it in conjunction with the flags where we export the location of includes and such.

(Also, I'm aware the lint failures aren't your fault. I need to get to them, but probably wont this week)

**Review by thomcc — APPROVED** [review]

**Comment by benmkw** [comment]
Sure, I just tested it and it fixes the problem as well (in my case) 🥳

**Comment by thomcc** [comment]
IDK when I'll get the next release out, but until then you can hopefully cope with a git dep?

**Comment by benmkw** [comment]
> IDK when I'll get the next release out, but until then you can hopefully cope with a git dep?

sure, no worry, thanks for your work 👍

**Pull request merged**
